"""initial_schema

Revision ID: 0ea52a560513
Revises: 
Create Date: 2026-09-10 19:30:05.340324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea52a560513'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('error_message', sa.String(length=500), nullable=True))
    op.add_column('analyses', sa.Column('overlay_filename', sa.String(length=255), nullable=True))
    op.add_column('analyses', sa.Column('result_data', sa.Text(), nullable=True))
    op.alter_column('benchmark_results', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'not_available'"))
    op.create_index(op.f('ix_benchmark_results_experiment_id'), 'benchmark_results', ['experiment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_benchmark_results_experiment_id'), table_name='benchmark_results')
    op.alter_column('benchmark_results', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'not_available'"))
    op.drop_column('analyses', 'result_data')
    op.drop_column('analyses', 'overlay_filename')
    op.drop_column('analyses', 'error_message')
    # ### end Alembic commands ###
